openapi: 3.0.1
info:
  title: '@jupiterone/graph-signal-sciences'
  description: A JupiterOne Integration for integesting data from Signal Sciences
  x-cortex-git:
    github:
      repository: JupiterOne/graph-signal-sciences
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-signal-sciences'
  x-cortex-service-groups:
    - tier-4
